//// <auto-generated />
//using DrinkAndGo.Data.Models;
//using Microsoft.EntityFrameworkCore;

//namespace DrinkAndGo.Data
//{
//    public class DrinkAndGoDbContext : DbContext
//    {
//        public DrinkAndGoDbContext(DbContextOptions<DrinkAndGoDbContext> options) : base(options)
//        {
//        }

//        public DbSet<Drink> Drinks { get; set; }
//        public DbSet<Category> Categories { get; set; }
//        public DbSet<ShoppingCartItem> ShoppingCartItems { get; set; }


//    }
//}
